### ISSUE TITLE
I got error when I execute "run_on_QPU.py"

### ISSUE THREAD

**Issue by masaya611** [XanaduAI/quantum-transfer-learning#14]
Hello.

I try to execute "run_on_QPU.py"
I got the error messages below.
----------------------------------
Traceback (most recent call last):
  File "/home/watabe/quantum-transfer-learning/quantum_processors/run_on_QPU.py", line 62, in <module>
    dev = qml.device("qiskit.ibmq", wires=n_qubits, backend="ibmqx4", ibmqx_token=token)
  File "/home/watabe/.tql/lib/python3.10/site-packages/pennylane/__init__.py", line 330, in device
    raise DeviceError("Device does not exist. Make sure the required plugin is installed.")
pennylane._device.DeviceError: Device does not exist. Make sure the required plugin is installed.
----------------------------------

I only change the token in this code.
Are there what I need to do?

**Comment by CatalinaAlbornoz** [comment]
Hi @masaya611!

You will need the pennylane-qiskit plugin. You can install it by using `python -m pip install pennylane-qiskit` . You can learn more about the plugin in its [documentation](https://docs.pennylane.ai/projects/qiskit/en/latest/index.html). 

Please let us know if this solves your problem!

**Comment by OnePl3** [comment]
After installing pennylane-qiskit, there is no ibmqx4 device.


```
dev = qml.device("qiskit.ibmq", wires=n_qubits, backend="ibmq_qasm_simulator", ibmqx_token=token, shots=1024)
print("Device capabilities: ", dev.capabilities()["backend"])
```
Device capabilities:  ['ibmq_qasm_simulator', 'ibmq_lima', 'ibmq_belem', 'ibmq_quito', 'simulator_statevector', 'simulator_mps', 'simulator_extended_stabilizer', 'simulator_stabilizer', 'ibmq_manila', 'ibm_nairobi', 'ibm_oslo']

**Comment by OnePl3** [comment]
Can you guys give me a new one, using the QPU example? This version is too old, and the IBM piece of equipment seems to be gone. Thank you very much!

**Comment by CatalinaAlbornoz** [comment]
Hi @OnePl3 , yes, as you noticed IBM no longer has the ibmqx4 device. However you can use ibmq_lima if you prefer. You just need to change the `run_on_QPU.py` file which is in folder `quantum_processors`. You can change the `"ibmqx4"` in line 62 to `"ibmq_lima"`. It is possible that other parts of the code are still outdated but at least this is an updated device that you can use.
